/*
 * Copyright 2025-present the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.github.darthakiranihil.konna.level.layer;

import io.github.darthakiranihil.konna.level.asset.KLevelMetadataCollection;

/**
 * Enumeration describing possible level types, assigned to a level transition.
 *
 * @since 0.5.0
 * @author Darth Akira Nihil
 */
public enum KTransitionedLevelType {

    /**
     * Level needs to be loaded from
     * {@link KLevelMetadataCollection}
     * from assigned asset.
     */
    PREDEFINED,
    /**
     * Level needs to be generated by
     * {@link io.github.darthakiranihil.konna.level.generator.KLevelGenerator}.
     */
    GENERATED

}
